image: dnscrypt-proxy
network: true
arches:
  - amd64
  - arm64
config:
  net: "host"
  binds:
    - /var:/var
    - /run:/run
    - /sys:/sys
    - /etc/ssl/certs:/etc/ssl/certs
  capabilities:
    - CAP_NET_BIND_SERVICE
